eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8084
spring:
  application:
    name: manager-zuul
 # sleuth:
 #  sampler:
  #    probability: 1.0
#  zipkin:
 #   baseurl: http://localhost:9411
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: manager-database

debug: true