eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8080
spring:
  application:
    name: manager-zuul
 # sleuth:
 #  sampler:
  #    probability: 1.0
#  zipkin:
 #   baseurl: http://localhost:9411
zuul:
  routes:
    web:
      path: /web/**
      serviceId: manager-web
    database:
      path: /database/**
      serviceId: manager-database
    redis:
      path: /redis/**
      serviceId: manager-redis
    common:
      path: /common/**
      serviceId: manager-common
debug: true