eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8080
spring:
  application:
    name: manager-zuul
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
   # password: zzctest123456
 # sleuth:
 #  sampler:
  #    probability: 1.0
#  zipkin:
 #   baseurl: http://localhost:9411
zuul:
  routes:
    web:
      path: /web/**
      serviceId: manager-web
      sensitiveHeaders: "*"
    database:
      path: /database/**
      serviceId: manager-database
      sensitiveHeaders: "*"
    redis:
      path: /redis/**
      serviceId: manager-redis
      sensitiveHeaders: "*"
    common:
      path: /common/**
      serviceId: manager-common
      sensitiveHeaders: "*"
debug: true