package com.chengzi.database.dao;

import com.chengzi.entity.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chengzi_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chengzi_user
     *
     * @mbggenerated
     */
    List<User> selectAll();
}