package com.chengzi.database.dao;

import com.chengzi.entity.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chengzi_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chengzi_user
     *
     * @mbggenerated
     */
    List<User> selectAll(Map map);

    User selectOne(int id);
    User selectOneByUserName(String username);
    int count();
    int update(User user);
}