package com.chengzi.entity;

public class User extends  BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chengzi_user.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chengzi_user.passWord
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chengzi_user.userName
     *
     * @return the value of chengzi_user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chengzi_user.userName
     *
     * @param username the value for chengzi_user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chengzi_user.passWord
     *
     * @return the value of chengzi_user.passWord
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chengzi_user.passWord
     *
     * @param password the value for chengzi_user.passWord
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}