package com.chengzi.entity;

import org.hibernate.validator.constraints.NotEmpty;
import org.json.JSONObject;

import javax.validation.constraints.NotBlank;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class User extends  BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chengzi_user.userName
     *
     * @mbggenerated
     */
   @NotBlank(message = "用户名不能为空")
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chengzi_user.passWord
     *
     * @mbggenerated
     */
    @NotBlank(message = "密码不能为空")
    private String password;

    private Date createTime;

    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chengzi_user.userName
     *
     * @return the value of chengzi_user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chengzi_user.userName
     *
     * @param username the value for chengzi_user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chengzi_user.passWord
     *
     * @return the value of chengzi_user.passWord
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chengzi_user.passWord
     *
     * @param password the value for chengzi_user.passWord
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
    public JSONObject toListJSONObject(){
        JSONObject jsonObject = new JSONObject();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        jsonObject.put("username",this.username);
        jsonObject.put("id",this.id);
        jsonObject.put("createTime",dateFormat.format(createTime));
        return jsonObject;
    }
}