server:
  port: 8085
spring:
  application:
    name: manager-common
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #password: zzctest123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/