server:
  port: 8083
spring:
  application:
    name: manager-web
  mvc:
    view:
      prefix: /
      suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/